# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class JobMetadata(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error: str=None, output: str=None):  # noqa: E501
        """JobMetadata - a model defined in Swagger

        :param error: The error of this JobMetadata.  # noqa: E501
        :type error: str
        :param output: The output of this JobMetadata.  # noqa: E501
        :type output: str
        """
        self.swagger_types = {
            'error': str,
            'output': str
        }

        self.attribute_map = {
            'error': 'error',
            'output': 'output'
        }
        self._error = error
        self._output = output

    @classmethod
    def from_dict(cls, dikt) -> 'JobMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobMetadata of this JobMetadata.  # noqa: E501
        :rtype: JobMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> str:
        """Gets the error of this JobMetadata.


        :return: The error of this JobMetadata.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this JobMetadata.


        :param error: The error of this JobMetadata.
        :type error: str
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501

        self._error = error

    @property
    def output(self) -> str:
        """Gets the output of this JobMetadata.


        :return: The output of this JobMetadata.
        :rtype: str
        """
        return self._output

    @output.setter
    def output(self, output: str):
        """Sets the output of this JobMetadata.


        :param output: The output of this JobMetadata.
        :type output: str
        """
        if output is None:
            raise ValueError("Invalid value for `output`, must not be `None`")  # noqa: E501

        self._output = output
