openapi: 3.0.0
info:
  description: |
    Design and implementation of an API to ease the use of HPC systems.
  version: "1.0.0"
  title: HPC RESTful API using Slurm
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: wajrcs@gmail.com
    name: Waqar Alamgir
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - description: HPC RESTful API using Slurm
    url: https://virtserver.swaggerhub.com/Master-Thesis/HPC-RESTful/1.0.0
  - url: 'https://HPC-RESTful.swagger.io/v2'
tags:
  - name: job
    description: Everything about HPC jobs
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: user
    description: Operations about users
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
paths:
  /job/findJobsByStatus:
    get:
      tags:
        - job
      summary: Finds jobs, optionally by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findJobsByStatus
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: false
          schema:
            type: array
            items:
              type: string
              enum:
                - new
                - cronjob_in_progress
                - hpc_queued
                - hpc_in_progress
                - cronjob_failed
                - hpc_failed
                - hpc_aborted
                - completed
        - name: pageLength
          in: query
          description: Number of records to return
          required: true
          schema:
            type: integer
            format: int64
        - name: pageNumber
          in: query
          description: Start index for paging
          required: true
          schema:
            type: integer
            format: int64
        - name: accessToken
          in: query
          description: Access token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: '#/components/schemas/PaginationResponse'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
        '400':
          description: Invalid status value
        '401':
          description: Unauthorized
  /job:
    post:
      tags:
        - job
      summary: Schedules a new job to the HPC system
      operationId: addJob
      parameters:
        - name: name
          in: query
          description: Name of the job
          required: true
          schema:
            type: string
        - name: command
          in: query
          description: Command of the job
          required: true
          schema:
            type: string
        - name: jobMetaData
          in: query
          description: Metadata of the job
          required: true
          schema:
            type: string
        - name: jobType
          in: query
          description: Type of the job
          required: true
          schema:
            type: string
            enum:
              - hpc
              - shell
        - name: accessToken
          in: query
          description: Access token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
            application/xml:
              schema:
                $ref: '#/components/schemas/Job'
        '405':
          description: Invalid input
        '401':
          description: Unauthorized
  /job/updateByOperation/{jobId}:
    put:
      tags:
        - job
      summary: Updates operation of an existing job
      operationId: updateJobByOperation
      parameters:
        - name: jobId
          in: path
          description: name that need to be updated
          required: true
          schema:
            type: integer
            format: int64
        - name: operation
          in: query
          description: Job Operation
          required: true
          schema:
            type: string
            enum:
              - queue
              - abort
        - name: accessToken
          in: query
          description: Access token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
            application/xml:
              schema:
                $ref: '#/components/schemas/Job'
        '400':
          description: Invalid ID supplied
        '404':
          description: Job not found
        '405':
          description: Validation exception
        '409':
          description: Job cannot be updated because of conflict with the current state of the resource
        '401':
          description: Unauthorized
  /job/{jobId}:
    get:
      tags:
        - job
      summary: Finds job by ID
      description: Returns a single job
      operationId: getJobById
      parameters:
        - name: jobId
          in: path
          description: ID of job to return
          required: true
          schema:
            type: integer
            format: int64
        - name: accessToken
          in: query
          description: Access token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
            application/xml:
              schema:
                $ref: '#/components/schemas/Job'
        '400':
          description: Invalid ID supplied
        '404':
          description: Job not found
        '401':
          description: Unauthorized
    put:
      tags:
        - job
      summary: Updates an existing job
      operationId: updateJob
      parameters:
        - name: jobId
          in: path
          description: ID of job to return
          required: true
          schema:
            type: integer
            format: int64
        - name: accessToken
          in: query
          description: Access token
          required: true
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/Job'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
            application/xml:
              schema:
                $ref: '#/components/schemas/Job'
        '400':
          description: Invalid ID supplied
        '404':
          description: Job not found
        '405':
          description: Validation exception
        '409':
          description: Job cannot be updated because of conflict with the current state of the resource
        '401':
          description: Unauthorized
    delete:
      tags:
        - job
      summary: Deletes an existing job
      operationId: deleteJob
      parameters:
        - name: jobId
          in: path
          description: Job id to delete
          required: true
          schema:
            type: integer
            format: int64
        - name: accessToken
          in: query
          description: Access token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Job not found
        '409':
          description: Job cannot be deleted because of conflict with the current state of the resource
        '401':
          description: Unauthorized
  /user/login:
    get:
      tags:
        - user
      summary: Logs user into the system
      operationId: loginUser
      parameters:
        - name: username
          in: query
          description: The user name for login
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: Invalid username/password supplied
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  schemas:
    JobMetadata:
      type: object
      properties:
        prerequisites:
          type: array
          items:
            type: string
        postrequisites:
          type: array
          items:
            type: string
        output:
          type: array
          items:
            type: string
      required:
        - prerequisites
        - postrequisites
        - output
    PaginationResponse:
      type: object
      properties:
        totalPages:
          type: number
        currentPage:
          type: number
        pageLength:
          type: number
        jobs:
          type: array
          items:
            $ref: '#/components/schemas/Job'
      xml:
        name: PaginationResponsedata
    User:
      type: object
      required:
        - username
        - firstName
        - lastName
        - email
        - password
      properties:
        userId:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        token:
          type: string
        userStatus:
          type: string
          description: User Status
          enum:
            - active
            - inactive
            - blocked
      xml:
        name: User
    Job:
      type: object
      required:
        - name
        - command
        - userId
      properties:
        jobId:
          type: integer
          format: int64
        hpcJobId:
          type: integer
          format: int64
        operation:
          type: string
          description: Job Operation
          enum:
            - queue
            - abort
        userId:
          type: integer
          format: int64
          description: User Id or GWDG account number
        name:
          type: string
        command:
          type: string
        jobMetaData:
          $ref: '#/components/schemas/JobMetadata'
        jobType:
          type: string
          description: Job Type
          enum:
            - hpc
            - shell
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
        result:
          type: string
        log:
          type: string
        status:
          type: string
          description: Job Status
          enum:
            - new
            - cronjob_in_progress
            - hpc_queued
            - hpc_in_progress
            - cronjob_failed
            - hpc_failed
            - hpc_aborted
            - completed
      xml:
        name: Job
  requestBodies:
    Job:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Job'
        application/xml:
          schema:
            $ref: '#/components/schemas/Job'
      description: Job object that needs to be added
      required: true